# Generated by Django 3.2.5 on 2021-07-20 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alerts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='seenby',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_seen_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seealert',
            name='alert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Alerts.alert'),
        ),
        migrations.AddField(
            model_name='seealert',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='alert_seen_by', to='Alerts.SeenBy'),
        ),
        migrations.AddField(
            model_name='alldatastr',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='rule_alert_target_groups', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='triggers',
            field=models.ManyToManyField(blank=True, to='Alerts.AllDataStr'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='rule_alert_target_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='alert',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='alert_target_groups', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='alert',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='alert_target_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
