version: "3.9"

services:
  web:
    depends_on:
      - postgres
      - redis
#      - rabbitmq
  postgres:
    image: postgres:12
  redis:
    image: redis
#  rabbitmq:
#    image: rabbitmq:latest

