# Generated by Django 3.2.4 on 2021-07-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_alter_datetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
