# Generated by Django 3.2.4 on 2021-07-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0004_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetype',
            name='description',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
