# Generated by Django 3.2.5 on 2021-07-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='limit',
            field=models.PositiveIntegerField(blank=True, help_text='if {absolute(latest measurement - the new measurement) == limit} then you may need to be alerted', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='column',
            name='max',
            field=models.PositiveIntegerField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='column',
            name='min',
            field=models.PositiveIntegerField(blank=True, max_length=500, null=True),
        ),
    ]
