# Generated by Django 3.2.4 on 2021-07-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alerts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='field_value',
            field=models.CharField(blank=True, help_text='If field value equal/gte/contains... then I will alert you', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='filter',
            field=models.CharField(blank=True, help_text='example: "oxgyn__lt=80"', max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='alldatastr',
            name='codename',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='alldatastr',
            name='name',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
