# Generated by Django 3.2.4 on 2021-07-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='code',
            field=models.CharField(max_length=999, unique=True),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=999, unique=True),
        ),
        migrations.AlterField(
            model_name='rpmplan',
            name='name',
            field=models.CharField(max_length=999, unique=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(max_length=999, unique=True),
        ),
    ]
