# Generated by Django 3.2.4 on 2021-07-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20210701_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cptcode',
            name='code',
            field=models.CharField(max_length=999, unique=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='title',
            field=models.CharField(max_length=999, unique=True),
        ),
        migrations.AlterField(
            model_name='roster',
            name='title',
            field=models.CharField(max_length=999, unique=True),
        ),
    ]
